# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 156fb8be2ecbae5211ed16e85e1aa3080bbe51f9d689ba08fa4e78d4d5568450107aa8f9df509e9156fb6b3ffca9203409b82c35ef0dd48f6be5c29207c206c2

test:
  secret_key_base: 9dd36a97e698450eb6c0087496dcb5985e412dc815d6652aa44a743a6bfa5b9bc6feac0775c2f1d1358ebbdba87f17d75ea710b1cabc0931ce4d507de62303ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
